FROM node:10-alpine
RUN mkdir -p /src/node_modules && chown -R node:node /src
USER node
WORKDIR /src
COPY src/queueApp/package*.json ./
RUN npm install
COPY --chown=node:node src/queueApp /src
CMD [ "node", "app.js" ]
