FROM node:10-alpine
RUN mkdir -p /src/node_modules && chown -R node:node /src
USER node
WORKDIR /src
COPY src/magicButton/package*.json ./
RUN npm install
COPY --chown=node:node src/magicButton /src
EXPOSE 8080
CMD [ "node", "app.js" ]
